### ISSUE TITLE
2 versions of compositeKey

### ISSUE THREAD

**Issue by zloirock** [bmeck/proposal-richer-keys#2]
`WeakMap` case is a good argument for returning objects from `compositeKey`. But object keys will not work, for example, on plain objects. I had some cases when it was required. Maybe add 2 versions of `compositeKey` method - the first returns objects, the second - symbols? Something like `compositeObject` / `compositeSymbol`?

**Comment by bmeck** [comment]
If I am understanding correctly it seems like `compositeSymbol` would be:

```mjs
const map = new WeakMap();
compositeSymbol = (...parts) => {
  const key = compositeKey(...parts);
  if (!map.has(key)) map.set(key, Symbol());
  return map.get(key);
}
```

?

**Comment by bmeck** [comment]
Do you have any requirements about cross realm needs for this? Like how `Symbol.for` is cross realm?

**Comment by zloirock** [comment]
Something like that. I haven't any strict position about cross-realm behaviour, but I think that it should be the same for both methods. AFAIK, it was discussed on the previous TC39 meeting.

**Comment by bmeck** [comment]
@zloirock currently there are no plans for cross realm idempotentcy and some vm implementors want it to be idempotent per realm so it would need a use case for why that would not be viable. I can split it up into two functions sometime this week, but committee might only want the Object form since it can be used to create the Symbol form. Big argument to standardize the Symbol form is to keep the cache the same across multiple code bases.

If you end up using the Symbol form, I'd appreciate a ping to the source code sometime.

**Comment by bmeck** [comment]
@zloirock I'm hesitant to use `Object` since while technically an object in the sense of `typeof` it isn't meant to be used like a regular object. I need to think on this, but would lean towards `compositeKey` + `compositeSymbol`.

**Comment by bmeck** [comment]
done
