### ISSUE TITLE
inner lifetime leak with WeakRefs

### ISSUE THREAD

**Issue by bmeck** [bmeck/proposal-richer-keys#3]
given:

```mjs
let a = {};
let $a = compositeKey(a);
const spy = MAKE_WEAK_REF($a, () => {
  console.log('thing inside $a collected');
});
$a = null;
```

spy would be be able to sniff when `a` gets collected without a direct reference to it. technically it would be tracking `$a`, but since the intended workflow is to usually hold `$a` weakly, this seems like something that needs to be discussed.

CC: @erights @dtribble

**Comment by dtribble** [comment]
A few options to preclude this:

1. throw an TypeError when attempt to make WeakCell that contains a composite key (same a if you make it with `undefined`).  
1. consider composite keys to be created "in a different realm" (the runtime's magic hash support realm) and so the WeakCell created with one is simply a strong reference.

The first option could be generalized in various ways (reject anything on a black list). The second seems better though, because it is simple and reuses an existing mechanism.

**Comment by erights** [comment]
I favor Dean's option 2. As with inter-realm pointing, it prevents observation of gc without preventing gc. Only the local pointer from the weakref to the target is made strong. If the weakref and target are both garbage, they can still be collected together.

**Comment by bmeck** [comment]
@dtribble @erights as @domenic pointed out, you can recreate this inner leak without a `compositeKey()` as well: 

```mjs
// a.mjs
let internal = new WeakMap();
export default a => {
  if (!internal.has(a)) {
    internal.set(a, {});
  }
  return internal.get(a);
};
```

```mjs
import getter from './a.mjs';

let a = {};
let $a = getter(a);
MAKE_WEAK_REF($a, () => {
  console.log('a collected');
});
$a = null;
```

I somewhat think it is a non-issue for this proposal at least in that light.

**Comment by erights** [comment]
I don't understand the example. The condition

```js
internal.has(a)
```

can never be false unless `a` is manually removed from the WeakMap. To ask the question, you must have `a`, therefore it cannot be collected during the question.

**Comment by bmeck** [comment]
This issue exists with or without this proposal.
